/*
 * MIT License
 *
 * Copyright (c) 2025 Riccardo Catervi
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * This software was designed and implemented as part of the academic
 * requirements of the "Programming Methodologies" course at
 * University of Camerino.
 */

package it.unicam.cs.mpgc.jbudget126139.service.mapper;

import it.unicam.cs.mpgc.jbudget126139.model.NormalAccount;
import it.unicam.cs.mpgc.jbudget126139.service.dto.AccountDTO;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.ReportingPolicy;
import org.mapstruct.factory.Mappers;

/**
 * Mapper interface for converting between {@link NormalAccount} entities
 * and {@link AccountDTO} data transfer objects.
 * <p>
 * Implementations are automatically generated by MapStruct at compile time.
 * </p>
 */
@Mapper(unmappedTargetPolicy = ReportingPolicy.ERROR)
public interface AccountMapper {

    /**
     * Singleton instance of the mapper generated by MapStruct.
     */
    AccountMapper INSTANCE = Mappers.getMapper(AccountMapper.class);

    /**
     * Converts a {@link NormalAccount} entity to its corresponding {@link AccountDTO}.
     *
     * @param entity the {@code NormalAccount} entity to convert
     * @return the corresponding {@code AccountDTO}
     */
    AccountDTO toDto(NormalAccount entity);

    /**
     * Converts an {@link AccountDTO} to a {@link NormalAccount} entity.
     * <p>
     * The following fields are ignored during mapping:
     * <ul>
     *     <li>{@code id} - generated by the persistence layer</li>
     *     <li>{@code createdAt} - managed automatically</li>
     *     <li>{@code transactions} - handled separately</li>
     * </ul>
     * </p>
     *
     * @param dto the {@code AccountDTO} to convert
     * @return the corresponding {@code NormalAccount} entity
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "transactions", ignore = true)
    // RIMUOVERE questa riga: @Mapping(target = "user", ignore = true)
    NormalAccount toEntity(AccountDTO dto);
}