/*
 * MIT License
 *
 * Copyright (c) 2025 Riccardo Catervi
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * This software was designed and implemented as part of the academic
 * requirements of the "Programming Methodologies" course at
 * University of Camerino.
 */

package it.unicam.cs.mpgc.jbudget126139.service.mapper;

import it.unicam.cs.mpgc.jbudget126139.model.NormalRecurrence;
import it.unicam.cs.mpgc.jbudget126139.service.dto.RecurrenceDTO;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.ReportingPolicy;
import org.mapstruct.factory.Mappers;

/**
 * Mapper interface for converting between {@link NormalRecurrence} entities
 * and {@link RecurrenceDTO} data transfer objects.
 * <p>
 * Implementations are automatically generated by MapStruct at compile time.
 * </p>
 */
@Mapper(unmappedTargetPolicy = ReportingPolicy.ERROR)
public interface RecurrenceMapper {

    /**
     * Singleton instance of the mapper generated by MapStruct.
     */
    RecurrenceMapper INSTANCE = Mappers.getMapper(RecurrenceMapper.class);

    /**
     * Converts a {@link NormalRecurrence} entity to its corresponding {@link RecurrenceDTO}.
     * <p>
     * The {@code account.id} field from the entity is mapped to the {@code accountId} field in the DTO.
     * </p>
     *
     * @param entity the {@code NormalRecurrence} entity to convert
     * @return the corresponding {@code RecurrenceDTO}
     */
    @Mapping(source = "account.id", target = "accountId")
    RecurrenceDTO toDto(NormalRecurrence entity);

    /**
     * Converts a {@link RecurrenceDTO} to a {@link NormalRecurrence} entity.
     * <p>
     * The following fields are ignored during mapping:
     * <ul>
     *     <li>{@code account} - set explicitly in the service layer</li>
     *     <li>{@code id} - generated by the persistence layer</li>
     *     <li>{@code createdAt} - managed automatically</li>
     * </ul>
     * </p>
     *
     * @param dto the {@code RecurrenceDTO} to convert
     * @return the corresponding {@code NormalRecurrence} entity
     */
    @Mapping(target = "account", ignore = true)
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    NormalRecurrence toEntity(RecurrenceDTO dto);
}