/*
 * MIT License
 *
 * Copyright (c) 2025 Riccardo Catervi
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * This software was designed and implemented as part of the academic
 * requirements of the "Programming Methodologies" course at
 * University of Camerino.
 */

package it.unicam.cs.mpgc.jbudget126139.service.mapper;

import it.unicam.cs.mpgc.jbudget126139.model.NormalTag;
import it.unicam.cs.mpgc.jbudget126139.service.dto.TagDTO;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.ReportingPolicy;
import org.mapstruct.factory.Mappers;

/**
 * Mapper interface for converting between {@link NormalTag} entities
 * and {@link TagDTO} data transfer objects.
 * <p>
 * Implementations are automatically generated by MapStruct at compile time.
 * </p>
 */
@Mapper(unmappedTargetPolicy = ReportingPolicy.ERROR)
public interface TagMapper {

    /**
     * Singleton instance of the mapper generated by MapStruct.
     */
    TagMapper INSTANCE = Mappers.getMapper(TagMapper.class);

    /**
     * Converts a {@link NormalTag} entity to its corresponding {@link TagDTO}.
     *
     * @param entity the {@code NormalTag} entity to convert
     * @return the corresponding {@code TagDTO}
     */
    TagDTO toDto(NormalTag entity);

    /**
     * Converts a {@link TagDTO} to a {@link NormalTag} entity.
     * <p>
     * The following fields are ignored during mapping:
     * <ul>
     *     <li>{@code id} - generated by the persistence layer</li>
     *     <li>{@code createdAt} - managed automatically</li>
     * </ul>
     * </p>
     *
     * @param dto the {@code TagDTO} to convert
     * @return the corresponding {@code NormalTag} entity
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    NormalTag toEntity(TagDTO dto);
}